apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
    volume.kubernetes.io/selected-node: gke-k8s01-pool-c3-free-86633c82-p9kh
    volume.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
  creationTimestamp: "2023-04-09T12:37:48Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: rahasak-elasticsearch
    elasticsearch.k8s.elastic.co/statefulset-name: rahasak-elasticsearch-es-client
  name: elasticsearch-data-rahasak-elasticsearch-es-client-0
  namespace: default
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1
    kind: Elasticsearch
    name: rahasak-elasticsearch
    uid: e4f343f6-d073-46ec-a24a-52c5bf4e769f
  resourceVersion: "67081141"
  uid: 451cf897-ecac-4ec5-9fbd-e30cf38ca684
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 11Gi
  storageClassName: standard-rwo
  volumeMode: Filesystem
  volumeName: pvc-451cf897-ecac-4ec5-9fbd-e30cf38ca684
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
