apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
    volume.kubernetes.io/selected-node: gke-k8s01-pool-c3-free-86633c82-p9kh
    volume.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
  creationTimestamp: "2023-04-09T12:37:47Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: rahasak-elasticsearch
    elasticsearch.k8s.elastic.co/statefulset-name: rahasak-elasticsearch-es-master
  name: elasticsearch-data-rahasak-elasticsearch-es-master-0
  namespace: default
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1
    kind: Elasticsearch
    name: rahasak-elasticsearch
    uid: e4f343f6-d073-46ec-a24a-52c5bf4e769f
  resourceVersion: "67081122"
  uid: 1fc42bb2-6686-44f3-adf0-75cd4fa813cb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 11Gi
  storageClassName: standard-rwo
  volumeMode: Filesystem
  volumeName: pvc-1fc42bb2-6686-44f3-adf0-75cd4fa813cb
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
