apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
    volume.kubernetes.io/selected-node: gke-k8s02-pool-n2-108d71af-3bg8
    volume.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
  creationTimestamp: "2023-04-12T20:14:04Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: rahasak-elasticsearch
    elasticsearch.k8s.elastic.co/statefulset-name: rahasak-elasticsearch-es-data
  name: elasticsearch-data-rahasak-elasticsearch-es-data-0
  namespace: default
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1
    kind: Elasticsearch
    name: rahasak-elasticsearch
    uid: b6838303-3eaf-42cb-b9ca-d86ef297fb49
  resourceVersion: "66171100"
  uid: 975ac2f9-2fe6-4ae3-87d6-5421920c8fd8
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 51Gi
  storageClassName: standard-rwo
  volumeMode: Filesystem
  volumeName: pvc-975ac2f9-2fe6-4ae3-87d6-5421920c8fd8
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
