apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: esrally
  name: esrally
  namespace: elastic
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: esrally
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: esrally
    spec:
      containers:
      - command:
        - /usr/local/bin/esrally
        - race
        - --track=geonames
        - --pipeline=benchmark-only
        - --report-format=csv
        - --report-file=/tmp/result.csv
        - --target-hosts=rahasak-elasticsearch-es-client:9200
        image: elastic/rally
        imagePullPolicy: Always
        name: rally
        resources: {}
      dnsPolicy: ClusterFirst
      nodeName: gke-k8s01-pool01-30f14dd0-t0hl
